/*Each new term in the Fibonacci sequence is 
generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci 
sequence whose values do not exceed four 
million, find the sum of the even-valued terms.*/

var fib = [];
fib[0] = 0;
fib[1] = 1;

var evenNumbers = [];

for(var n = 1; fib[n] < 4000000; n++) {
	fib[n+1] = (fib[n] + fib[n-1]); 
	
	if(fib[n+1] % 2 == 0) {
		evenNumbers.push(fib[n+1]);
	}
};

var total = 0;
for(j = 0; j < evenNumbers.length; j++) {
	total += evenNumbers[j];
}

console.log(evenNumbers);
console.log(total);
